export const colors = {
    primary: '#007bff',
    success: '#28a745',
    danger: '#dc3545',
    warning: '#ffc107',
    secondary: '#6c757d',
    dark: '#343a40',
    light: '#f8f9fa',
    white: '#ffffff',
    black: '#333333',
    gray: '#6c757d',
    lightGray: '#e9ecef',
    border: '#dee2e6',
    errorBg: '#f8d7da',
    errorText: '#721c24',
    successBg: '#d4edda',
    successText: '#155724',
};

export const spacing = {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    xxl: '3rem',
};

export const borderRadius = {
    sm: '4px',
    md: '8px',
    lg: '12px',
    round: '50%',
};

export const fontSize = {
    xs: '0.75rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    xxl: '1.5rem',
};

export const commonStyles = {
    container: {
        padding: spacing.xl,
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: spacing.lg,
        flexWrap: 'wrap',
        gap: spacing.md,
    },
    title: {
        fontSize: fontSize.xxl,
        fontWeight: 'bold',
        color: colors.dark,
        margin: 0,
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse',
        backgroundColor: colors.white,
    },
    th: {
        border: `1px solid ${colors.border}`,
        padding: spacing.sm,
        textAlign: 'left',
        backgroundColor: colors.lightGray,
        fontWeight: 'bold',
    },
    td: {
        border: `1px solid ${colors.border}`,
        padding: spacing.sm,
    },
    button: {
        backgroundColor: colors.primary,
        color: colors.white,
        border: 'none',
        padding: `${spacing.sm} ${spacing.md}`,
        borderRadius: borderRadius.sm,
        cursor: 'pointer',
        fontSize: fontSize.sm,
        transition: 'all 0.2s',
    },
    editBtn: {
        backgroundColor: colors.warning,
        color: colors.black,
        border: 'none',
        padding: `${spacing.xs} ${spacing.sm}`,
        borderRadius: borderRadius.sm,
        cursor: 'pointer',
        marginRight: spacing.sm,
        fontSize: fontSize.xs,
    },
    deleteBtn: {
        backgroundColor: colors.danger,
        color: colors.white,
        border: 'none',
        padding: `${spacing.xs} ${spacing.sm}`,
        borderRadius: borderRadius.sm,
        cursor: 'pointer',
        fontSize: fontSize.xs,
    },
    cancelBtn: {
        backgroundColor: colors.secondary,
        color: colors.white,
        border: 'none',
        padding: `${spacing.sm} ${spacing.md}`,
        borderRadius: borderRadius.sm,
        cursor: 'pointer',
        marginLeft: spacing.sm,
    },
    formContainer: {
        marginTop: spacing.xl,
        padding: spacing.md,
        border: `1px solid ${colors.border}`,
        borderRadius: borderRadius.md,
        backgroundColor: colors.white,
        marginBottom: spacing.xl,
    },
    formRow: {
        display: 'flex',
        gap: spacing.md,
        flexWrap: 'wrap',
    },
    formGroup: {
        flex: 1,
        minWidth: '200px',
    },
    label: {
        display: 'block',
        marginBottom: spacing.xs,
        fontWeight: 'bold',
        fontSize: fontSize.sm,
    },
    input: {
        width: '100%',
        padding: spacing.sm,
        border: `1px solid ${colors.border}`,
        borderRadius: borderRadius.sm,
        boxSizing: 'border-box',
        fontSize: fontSize.sm,
    },
    select: {
        width: '100%',
        padding: spacing.sm,
        border: `1px solid ${colors.border}`,
        borderRadius: borderRadius.sm,
        boxSizing: 'border-box',
    },
    error: {
        backgroundColor: colors.errorBg,
        color: colors.errorText,
        padding: spacing.sm,
        borderRadius: borderRadius.sm,
        marginBottom: spacing.md,
    },
    success: {
        backgroundColor: colors.successBg,
        color: colors.successText,
        padding: spacing.sm,
        borderRadius: borderRadius.sm,
        marginBottom: spacing.md,
    },
    pagination: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: spacing.sm,
        marginTop: spacing.xl,
        flexWrap: 'wrap',
    },
    pageButton: {
        backgroundColor: colors.lightGray,
        color: colors.dark,
        border: `1px solid ${colors.border}`,
        padding: `${spacing.xs} ${spacing.md}`,
        borderRadius: borderRadius.sm,
        cursor: 'pointer',
        fontSize: fontSize.sm,
    },
    activePageButton: {
        backgroundColor: colors.primary,
        color: colors.white,
        border: `1px solid ${colors.primary}`,
        padding: `${spacing.xs} ${spacing.md}`,
        borderRadius: borderRadius.sm,
        cursor: 'pointer',
        fontSize: fontSize.sm,
    },
    pageInfo: {
        margin: `0 ${spacing.md}`,
        fontSize: fontSize.sm,
        color: colors.gray,
    },
};